- Inbbbox/Source Files/ViewControllers/TwoLayoutsCollectionViewController.swift
[IOS-500](https://netguru.atlassian.net/browse/IOS-500)
fix two column layout glitch when header with author disappears 
https://monosnap.com/file/kZj4ate03Jy1SgRYDU5GtNaxJFphKm
> [IOS-500]fix two column layout glitch

- Inbbbox/Source Files/Views/Controllers View/ShotDetailsView.swift
- Unit Tests/APIAttachmentsProviderSpec.swift
[IOS-551](https://netguru.atlassian.net/browse/IOS-551)
Will be merged after https://github.com/netguru/inbbbox-ios/pull/327
> IOS-551 App is crashing in shot details view

- Inbbbox/Resources/Images.xcassets/AppIcon-co.netguru.inbbbox.appiconset/Contents.json
- Inbbbox/Resources/Images.xcassets/AppIcon-co.netguru.inbbbox.staging.appiconset/Contents.json
- Inbbbox/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
- Inbbbox/Source Files/Managers/Animators/LoginViewAnimations.swift
- Podfile
- Podfile.lock
[IOS-553](https://netguru.atlassian.net/browse/IOS-553)
Remove Pod which was causing problems with animations
> [IOS-553] Fix cells animation glitch

- Inbbbox.xcodeproj/project.pbxproj
[IOS-575](https://netguru.atlassian.net/browse/IOS-575)
Set proper provisioning profile for staging
> [IOS-575] Set proper provisioning profile for staging

- README.md
[IOS-580](https://netguru.atlassian.net/browse/IOS-580)
Update readme
> [IOS-580] Update readme

- Inbbbox.xcodeproj/project.pbxproj
[IOS-575](https://netguru.atlassian.net/browse/IOS-575)
Update code signing identities
> [IOS-575] Update code signing identities

- Inbbbox/Source Files/Views/UICollectionViewCell/ShotDetailsCommentCollectionViewCell.swift
[IOS-525](https://netguru.atlassian.net/browse/IOS-525)
Fix comments which are cut
> IOS-525: Cut comment fix

- Inbbbox.xcodeproj/project.pbxproj
[IOS-575](https://netguru.atlassian.net/browse/IOS-575)
Set code signing to manual
> [IOS-575] Set code signing to manual

- Inbbbox/Source Files/Managers/Shots State Handlers/ShotsNormalStateHandler.swift
- Inbbbox/Source Files/Model/DayMode.swift
- Inbbbox/Source Files/Model/NightMode.swift
- Inbbbox/Source Files/Protocols/ColorModeType.swift
- Inbbbox/Source Files/Providers/ColorModeProvider.swift
[IOS-523](https://netguru.atlassian.net/browse/IOS-523)
> [IOS-523] After onboarding background is black for the moment + logo is sliding from bottom of the screen

- Inbbbox/Source Files/Providers/API Providers/PageableProvider.swift
[IOS-557](https://netguru.atlassian.net/browse/IOS-557)
Added one extra condition in preparations data for page because sometimes there were situations when $0 was nil.
> [IOS-557] Crash in PageableProvide

- Inbbbox/Source Files/Managers/FlashMessage.swift
- Inbbbox/Source Files/ViewControllers/SettingsViewController.swift
- Inbbbox/Source Files/Views/Custom/FlashMessageView.swift
[IOS-526](https://netguru.atlassian.net/browse/IOS-526)
Added possibility that flashmessage will not be displayed in current view but in keyWindow instead
> [IOS-526] I don't see flash message when I am on the bottom of the page

- Inbbbox/Source Files/Extensions/GalleryViewProvider.swift
- Inbbbox/Source Files/Model/DayMode.swift
- Inbbbox/Source Files/Model/NightMode.swift
- Inbbbox/Source Files/Protocols/ColorModeType.swift
- Inbbbox/Source Files/Providers/EstimatedLocationProvider.swift
- Inbbbox/Source Files/ViewControllers/ShotDetailsViewController.swift
- Inbbbox/Source Files/Views/Custom/ShotDetailsHeaderView.swift
- Unit Tests/SettingsViewModelSpec.swift
[IOS-520](https://netguru.atlassian.net/browse/IOS-520)
Improve showing full screen attachment animation
> [IOS-520] Improve showing full screen attachment animation

- Inbbbox/Source Files/Views/Custom/ShotImageView.swift
[IOS-585](https://netguru.atlassian.net/browse/IOS-585)
Added guard for bluredImage and removed not needed anymore comment.
> [IOS-585] Sometimes application crash when in method ShotImageView.applyBlur bluredImage is nil

- Inbbbox.xcodeproj/project.pbxproj
- Inbbbox/Source Files/Managers/Shots State Handlers/ShotsNormalStateHandler.swift
- Inbbbox/Source Files/Protocols/Vibratable.swift
- Inbbbox/Source Files/ViewControllers/ShotBucketsViewController.swift
- Inbbbox/Source Files/ViewControllers/ShotsCollectionViewController.swift
- Inbbbox/Source Files/ViewModels/ShotDetailsViewModel.swift
- Inbbbox/Source Files/ViewModels/TeamDetailsViewModel.swift
- Inbbbox/Source Files/ViewModels/UserDetailsViewModel.swift
[IOS-583](https://netguru.atlassian.net/browse/IOS-583)
Phone should vibrate when user presses like, follow or add to bucket
> IOS-583: Haptic feedback for liking, following and adding to bucket

- Unit Tests/ShotCollectionViewCellSpec.swift
[IOS-425](https://netguru.atlassian.net/browse/IOS-425)
Fix Pending Specs
> [IOS-425] Fix Pending Specs

- Inbbbox.xcodeproj/project.pbxproj
- Inbbbox/Source Files/Managers/Shots State Handlers/ShotsNormalStateHandler.swift
- Inbbbox/Source Files/Providers/Shots/ShotsProvider.swift
- Inbbbox/Source Files/Storages/Cache.swift
- Inbbbox/Source Files/ViewControllers/CenterButtonTabBarController.swift
- Inbbbox/Source Files/ViewControllers/ShotDetailsViewController.swift
- Inbbbox/Source Files/ViewModels/ShotDetailsViewModel.swift
- Unit Tests/ShotsProviderSpec.swift
[IOS-586](https://netguru.atlassian.net/browse/IOS-586)
Tests for Cache will be implemented in separate task.
> [IOS-586] Cache.

- Inbbbox/Source Files/ViewControllers/BucketsCollectionViewController.swift
- Inbbbox/Source Files/ViewControllers/SimpleShotsCollectionViewController.swift
- Inbbbox/Source Files/ViewModels/BucketContentViewModel.swift
- Inbbbox/Source Files/ViewModels/BucketsViewModel.swift
- Unit Tests/BucketsViewModelSpec.swift
Reverts netguru/inbbbox-ios#370
> IOS-588: Inject Bucket details from previous screen - revert

- Inbbbox/Source Files/ViewControllers/SimpleShotsCollectionViewController.swift
[IOS-598](https://netguru.atlassian.net/browse/IOS-598)
Passed cell for which photos should be downloaded
> [IOS-598] Shots on likes view not visible

- Inbbbox.xcodeproj/project.pbxproj
- Inbbbox/Source Files/Protocols/Support3DTouch.swift
- Inbbbox/Source Files/ViewControllers/BucketsCollectionViewController.swift
- Inbbbox/Source Files/ViewControllers/FolloweesCollectionViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileViewController.swift
- Inbbbox/Source Files/ViewControllers/ShotsCollectionViewController.swift
- Inbbbox/Source Files/ViewControllers/SimpleShotsCollectionViewController.swift
[IOS-540](https://netguru.atlassian.net/browse/IOS-540)
Regarding to #369 there was still bug with misplaced previewingContext that occures when the list was scrolled.
> [IOS-540] 3D touch support for the older version of iPhones

- Inbbbox/Source Files/ViewModels/SettingsViewModel.swift
[IOS-533](https://netguru.atlassian.net/browse/IOS-533)
Invoking setup on Color Provider
> [IOS-533] Auto night mode

- Inbbbox/Resources/de.lproj/InfoPlist.strings
- Inbbbox/Resources/de.lproj/Localizable.strings
- Inbbbox/Resources/es.lproj/InfoPlist.strings
- Inbbbox/Resources/es.lproj/Localizable.strings
- Inbbbox/Resources/fr.lproj/InfoPlist.strings
- Inbbbox/Resources/fr.lproj/Localizable.strings
- Inbbbox/Resources/pl.lproj/InfoPlist.strings
- Inbbbox/Resources/pl.lproj/Localizable.strings
- Inbbbox/Resources/pt-PT.lproj/InfoPlist.strings
- Inbbbox/Resources/pt-PT.lproj/Localizable.strings
[IOS-615](https://netguru.atlassian.net/browse/IOS-615)
> [IOS-615] Missing translations

- Inbbbox.xcodeproj/project.pbxproj
- Inbbbox/Source Files/Networking/APIRateLimitKeeper.swift
- Inbbbox/Source Files/Providers/Core Data Providers/Buckets/ManagedBucketsProvider.swift
- Inbbbox/Source Files/Providers/Core Data Providers/Buckets/ManagedBucketsRequester.swift
- Inbbbox/Source Files/Providers/Core Data Providers/Projects/ManagedProjectsProvider.swift
- Inbbbox/Source Files/StoreData.xcdatamodeld/.xccurrentversion
- Inbbbox/Source Files/StoreData.xcdatamodeld/StoreData 2.xcdatamodel/contents
- Inbbbox/Source Files/StoreData.xcdatamodeld/StoreData 3.xcdatamodel/contents
- Unit Tests/APIUsersProviderSpec.swift
- Unit Tests/ArrayExtensionSpec.swift
- Unit Tests/CollectionExtensionSpec.swift
- Unit Tests/LazyImageProviderSpec.swift
- Unit Tests/ManagedBucketsProviderSpec.swift
- Unit Tests/ManagedBucketsRequesterSpec.swift
- Unit Tests/ManagedProjectsProviderSpec.swift
- Unit Tests/ShotsOnboardingStateHandlerSpec.swift
- Unit Tests/ShotsStateHandlersProviderSpec.swift
- bitrise.yml
[IOSS-44](https://netguru.atlassian.net/browse/IOSS-44)
Add more tests
> [IOSS-44] Add more tests

- Inbbbox/Source Files/AppDelegate.swift
- Inbbbox/Source Files/Settings.swift
- Inbbbox/Source Files/ViewControllers/ShotsCollectionViewController.swift
[IOS-556](https://netguru.atlassian.net/browse/IOS-556)
* Open home view
* standard "showing you X" animation starts and finishes
* down arrow fades in (~1s)
* down arrow fades out slowly in (5s) but when clicking the logo dropdown/modal appears
* all sources + my set from settings are available
* clicking outside of the list closes modal
Fix: Stream sources displayed after every change.
> [IOS-556] Stream change on the main screen - fix

- Inbbbox/Resources/de.lproj/InfoPlist.strings
- Inbbbox/Resources/de.lproj/Localizable.strings
- Inbbbox/Resources/es.lproj/InfoPlist.strings
- Inbbbox/Resources/es.lproj/Localizable.strings
- Inbbbox/Resources/fr.lproj/InfoPlist.strings
- Inbbbox/Resources/fr.lproj/Localizable.strings
- Inbbbox/Resources/pl.lproj/InfoPlist.strings
- Inbbbox/Resources/pl.lproj/Localizable.strings
- Inbbbox/Resources/pt-PT.lproj/InfoPlist.strings
- Inbbbox/Resources/pt-PT.lproj/Localizable.strings
[IOS-622](https://netguru.atlassian.net/browse/IOS-622)
> IOS-622 Add translations to Inbbbox

- Inbbbox.xcodeproj/project.pbxproj
- Inbbbox/Source Files/Managers/Shots State Handlers/ShotsNormalStateHandler.swift
- Inbbbox/Source Files/Model/LikedShot.swift
- Inbbbox/Source Files/Model/Shot.swift
- Inbbbox/Source Files/Protocols/Sortable.swift
- Inbbbox/Source Files/Providers/API Providers/APILikedShotsProvider.swift
- Inbbbox/Source Files/Providers/API Providers/APIShotsProvider.swift
- Inbbbox/Source Files/Providers/API Providers/APIShotsRequester.swift
- Inbbbox/Source Files/Providers/Core Data Providers/Shots/ManagedShotsProvider.swift
- Inbbbox/Source Files/Providers/Core Data Providers/Shots/ManagedShotsRequester.swift
- Inbbbox/Source Files/Providers/Shots/ShotsProvider.swift
- Inbbbox/Source Files/Providers/Shots/ShotsRequester.swift
- Inbbbox/Source Files/Storages/Cache.swift
- Inbbbox/Source Files/ViewModels/LikesViewModel.swift
- Inbbbox/Source Files/ViewModels/ShotDetailsViewModel.swift
- Unit Tests/APIShotsRequesterSpec.swift
- Unit Tests/Mock Objects/APILikedShotsProviderMock.swift
- Unit Tests/Mock Objects/ManagedShotsProviderMock.swift
- Unit Tests/ShotsProviderSpec.swift
[IOS-605](https://netguru.atlassian.net/browse/IOS-605)
> [IOS-605] Check how we can sort likes

- Inbbbox/Source Files/Extensions/UIViewExtension.swift
- Inbbbox/Source Files/Protocols/Support3DTouch.swift
- Inbbbox/Source Files/ViewControllers/BucketsCollectionViewController.swift
- Inbbbox/Source Files/ViewControllers/FolloweesCollectionViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileViewController.swift
[IOS-540](https://netguru.atlassian.net/browse/IOS-540)
3D touch support for the older version of iPhones
Fixes: expanded area of sourceRect For PeekPop's `PreviewingContext` & added compatibility for all iPhones below 6s version
> [IOS-540] 3D touch support for the older version of iPhones improvements

- Inbbbox/Source Files/ViewControllers/ProfileInfoViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileShotsOrMembersViewController.swift
[IOS-606](https://netguru.atlassian.net/browse/IOS-606)
Change view controller that shows flash messages
> IOS-606: Change view controller that shows flash messages

- Inbbbox/Source Files/Extensions/GalleryViewProvider.swift
[IOS-617](https://netguru.atlassian.net/browse/IOS-617)
Changed frame of button to have bigger tap area
> [IOS-617] Close button on the full shot view doesn't work properly

- Inbbbox.xcodeproj/project.pbxproj
- Inbbbox/Source Files/Helpers/ManagedObjectsProvider.swift
- Inbbbox/Source Files/StoreData.xcdatamodeld/.xccurrentversion
- Inbbbox/Source Files/StoreData.xcdatamodeld/StoreData 4.xcdatamodel/contents
- Unit Tests/Resources/User.json
- Unit Tests/UserSpec.swift
[IOS-629](https://netguru.atlassian.net/browse/IOS-629)
Adjust Core Data model
> IOS-629: Adjust Core Data model

- Inbbbox/Source Files/Views/UICollectionViewCell/ShotCollectionViewCell.swift
[IOS-619](https://netguru.atlassian.net/browse/IOS-619)
Implemented hiding unnecessary image views
> [IOS-619] On swiping left and right - part of other icon is visible

- Inbbbox/Source Files/Model/ManagedObjects/ManagedUser.swift
- Inbbbox/Source Files/Model/Protocols/UserType.swift
- Inbbbox/Source Files/Model/User.swift
- Inbbbox/Source Files/StoreData.xcdatamodeld/StoreData 4.xcdatamodel/contents
- Inbbbox/Source Files/ViewControllers/ProfileViewController.swift
- Inbbbox/Source Files/Views/Controllers View/ProfileView.swift
- Inbbbox/Source Files/Views/Custom/ProfileHeaderView.swift
- Unit Tests/Resources/User.json
- Unit Tests/UserSpec.swift
[IOS-606](https://netguru.atlassian.net/browse/IOS-606)
- Add badge on profile avatar
- change alpha while hiding header
> IOS-606: Add badge on profile avatar

- Inbbbox.xcodeproj/project.pbxproj
- Inbbbox/Source Files/Extensions/UIScrollViewExtension.swift
- Inbbbox/Source Files/ViewControllers/ProfileProjectsOrBucketsViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileShotsViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileViewController.swift
- Inbbbox/Source Files/Views/Controllers View/ProfileView.swift
- Inbbbox/Source Files/Views/Custom/ProfileHeaderView.swift
[IOS-640](https://netguru.atlassian.net/browse/IOS-640)
Make UX better on profile view. Achieved by observing `contentOffset` and adjusting scrollable views within PageViewController.
> IOS-640: Make UX better on profile view.

- Inbbbox/Source Files/Managers/Shots State Handlers/ShotsInitialAnimationsStateHandler.swift
- Inbbbox/Source Files/Managers/Shots State Handlers/ShotsNormalStateHandler.swift
[IOS-655](https://netguru.atlassian.net/browse/IOS-655)
App sometimes crashes if I set off all 'stream sources' and click between tabs (it crashes on central tab with inbbbox icon) 
http://take.ms/ITXxq
> IOS-655: App sometimes crashes if I set off all 'stream sources' and click between tabs

- Inbbbox/Source Files/ViewControllers/ProfileInfoViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileProjectsOrBucketsViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileShotsViewController.swift
- Inbbbox/Source Files/ViewModels/SettingsViewModel.swift
- Unit Tests/SettingsViewModelSpec.swift
… for layoutIfNeeded
[IOS-645](https://netguru.atlassian.net/browse/IOS-645)
Added language option for guests, changed Async invokes with delay for layoutIfNeeded
> IOS-645: Missing language option in the guest mode

- Inbbbox/Source Files/Extensions/GalleryViewProvider.swift
- Inbbbox/Source Files/Views/Custom/AnimatableShotImageView.swift
- Podfile
- Podfile.lock
[IOS-651](https://netguru.atlassian.net/browse/IOS-651)
For some reason animatedImage was not set when loading without animation.
> IOS-651: attachment is loading forever

- Inbbbox/Resources/de.lproj/InfoPlist.strings
- Inbbbox/Resources/de.lproj/Localizable.strings
- Inbbbox/Resources/es.lproj/Localizable.strings
- Inbbbox/Resources/fr.lproj/Localizable.strings
- Inbbbox/Resources/pt-PT.lproj/Localizable.strings
[IOS-658](https://netguru.atlassian.net/browse/IOS-658)
Added missing translations.
> IOS-658: Add translations to Inbbbox

- Inbbbox/Source Files/ViewControllers/ShotDetailsViewController.swift
- Inbbbox/Source Files/Views/Custom/ShotDetailsFooterView.swift
[IOS-652](https://netguru.atlassian.net/browse/IOS-652)
Fix for jumping ball while loading comments.
> IOS-652: Fix for jumping ball while loading comments.

- Inbbbox/Resources/pl.lproj/Localizable.strings
[IOS-656](https://netguru.atlassian.net/browse/IOS-656)
Fixed typo in polish translation
> IOS-656: typo: Polish language "ładuje" on loading.

- Inbbbox/Source Files/ViewControllers/SettingsViewController.swift
- Inbbbox/Source Files/ViewModels/SettingsViewModel.swift
[IOS-654](https://netguru.atlassian.net/browse/IOS-654)
Hide dateItem in setting according to date toggle state.
> IOS-654: It's possible to set timer at specific hour even if this option is set off

- Inbbbox/Source Files/Views/Custom/ShotsCollectionBackgroundView.swift
[IOS-648](https://netguru.atlassian.net/browse/IOS-648)
Changed constraint to hide arrow
> IOS-648: Arrow not hiding fix

- Inbbbox/Source Files/ViewControllers/ProfileViewController.swift
[IOS-650](https://netguru.atlassian.net/browse/IOS-650)
Fix night mode change on followings view
> IOS-650: Fix night mode change on followings view

- Inbbbox/Source Files/Views/UITableViewCell/SwitchCell.swift
[IOS-666](https://netguru.atlassian.net/browse/IOS-666)
Fix for: `Cell with reminder switch is broken on Settings view`
> IOS-666: Cell with reminder switch is broken on Settings view

- Inbbbox/Source Files/Managers/ShotDetailsPageViewControllerDataSource.swift
- Inbbbox/Source Files/ViewControllers/ProfileProjectsOrBucketsViewController.swift
- Inbbbox/Source Files/ViewControllers/ShotDetailsViewControllerExtension.swift
- Inbbbox/Source Files/Views/Custom/AvatarView.swift
- Inbbbox/Source Files/Views/UITableViewCell/CarouselCell.swift
[IOS-608](https://netguru.atlassian.net/browse/IOS-608)
Profile of the user - create a vertical cell.
Displaying shot details only worked by a 3D Touch gesture. CarouselCellDelegate needs to be created to present shot details also after a single tap.
> IOS-608: Fix for missing cell delegate

- Inbbbox/Source Files/Managers/AnalyticsManager.swift
- Inbbbox/Source Files/Providers/API Providers/APIConnectionsRequester.swift
[IOS-669](https://netguru.atlassian.net/browse/IOS-669)
Added follow user tracking event
> IOS-669: Added follow user tracking event

- Inbbbox/Source Files/Networking/Queries/ShotsQuery.swift
[IOS-671](https://netguru.atlassian.net/browse/IOS-671)
When viewing team profile not all shots where displayed.
> IOS-671: wrong number of shots

- Inbbbox/Source Files/ViewControllers/ProfileInfoViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileProjectsOrBucketsViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileShotsViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileViewController.swift
[IOS-676](https://netguru.atlassian.net/browse/IOS-676)
Fix `info` tab scrolling on profile view.
> IOS-676: Fix `info` tab scrolling on profile view.

- Inbbbox/Source Files/Views/Controllers View/ProfileView.swift
- Inbbbox/Source Files/Views/Custom/ProfileHeaderView.swift
[IOS-674](https://netguru.atlassian.net/browse/IOS-674)
Adjusted top constraint to move along with header.
> IOS-674: User profile background animation is not working

- Inbbbox/Source Files/Views/Custom/ProfileMenuBarView.swift
- Inbbbox/Source Files/Views/Custom/ProfileMenuButton.swift
[IOS-673](https://netguru.atlassian.net/browse/IOS-673)
This PR introduce:
- fix `nameLabel.textColor` in night mode
> [IOS-673] Text color in profile tabBar is black

- Inbbbox/Source Files/Managers/Shots State Handlers/ShotsOnboardingStateHandler.swift
- Inbbbox/Source Files/Networking/Queries/TeamMembersQuery.swift
- Inbbbox/Source Files/Providers/API Providers/APITeamsProvider.swift
- Inbbbox/Source Files/Providers/Teams/TeamsProvider.swift
- Inbbbox/Source Files/ViewControllers/ProfileInfoViewController.swift
- Inbbbox/Source Files/ViewModels/FolloweesViewModel.swift
- Inbbbox/Source Files/ViewModels/ProfileInfoViewModel.swift
- Inbbbox/Source Files/Views/Controllers View/ProfileInfoView.swift
- Unit Tests/APITeamsProviderSpec.swift
[IOS-607](https://netguru.atlassian.net/browse/IOS-607)
[IOS-667](https://netguru.atlassian.net/browse/IOS-667)
Added possibility to access teams of user through info tab, added possibility to watch shot's details from info tab, night mode fixed, fixed bug when UI freezed when there were no shots to display
> [IOS-607, IOS-667] Freezing UI fix and profile info improvements

- Inbbbox/Source Files/Views/Custom/ProfileMenuBarView.swift
- Inbbbox/Source Files/Views/Custom/ProfileMenuButton.swift
[IOS-696](https://netguru.atlassian.net/browse/IOS-696)
This PR introduce:
- Fix for situation when initial font for nameLabel is wrong.
> [IOS-696] Initial font for nameLabel is incorrect

- Inbbbox/Source Files/ViewControllers/ProfileShotsViewController.swift
[IOS-697](https://netguru.atlassian.net/browse/IOS-697)
Fix sharp corners on shots in profile view
> IOS-697: Fix sharp corners on shots in profile view

- Inbbbox/Source Files/ViewControllers/ProfileInfoViewController.swift
[IOS-607](https://netguru.atlassian.net/browse/IOS-607)
Removed unnecessary overriding user in shot
> IOS-607: Fixing displaying user in shot details

- Inbbbox/Source Files/ViewControllers/ProfileInfoViewController.swift
[IOS-607](https://netguru.atlassian.net/browse/IOS-607)
Mapping all user's shots to contain user info
> IOS-607: Attaching user to all shots

- Inbbbox/Source Files/ViewControllers/ShotBucketsViewController.swift
[IOS-699](https://netguru.atlassian.net/browse/IOS-699)
Fix broken collection on `Add to bucket` view
> IOS-699: Fix broken collection on `Add to bucket` view

- Inbbbox/Source Files/Views/Controllers View/ProfileInfoView.swift
- Inbbbox/Source Files/Views/Custom/ShotsCollectionBackgroundView.swift
[IOS-710](https://netguru.atlassian.net/browse/IOS-710)
The Inbbbox app got rejected again by Apple. Good news: they approved our changes for blocking users. Bad news: we have to fix some things for iPad display.
> IOS-710: Proper displaying on iPad at iPhone resolution

- Inbbbox/Source Files/Views/UICollectionViewCell/BucketCollectionViewCell.swift
[IOS-712](https://netguru.atlassian.net/browse/IOS-712)
AS IS
https://monosnap.com/file/QXcnUBiJzYhN1mU537ytOKYWD86kIP
after creating new bucket, it has pictures from other bucket
TO BE
I should see placeholder
> [IOS-712]: After creating new bucket, it has pictures from other bucket

- Inbbbox/Source Files/Helpers/CustomTransitions.swift
- Inbbbox/Source Files/Managers/Shots State Handlers/ShotsNormalStateHandler.swift
- Inbbbox/Source Files/ViewControllers/ProfileInfoViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileProjectsOrBucketsViewController.swift
- Inbbbox/Source Files/ViewControllers/ProfileShotsViewController.swift
- Inbbbox/Source Files/ViewControllers/ShotDetailsPageViewController.swift
- Inbbbox/Source Files/ViewControllers/ShotDetailsViewController.swift
- Inbbbox/Source Files/ViewControllers/SimpleShotsCollectionViewController.swift
[IOS-711](https://netguru.atlassian.net/browse/IOS-711)
Solution for problem: `it is very hard to scroll up shot details`
> IOS-711: It is very hard to scroll up shot details

- Inbbbox/Source Files/Views/Custom/ShotsCollectionBackgroundView.swift
[IOS-713](https://netguru.atlassian.net/browse/IOS-713)
AS IS
https://monosnap.com/file/x4cqTvY67nnPBV2Aylr3o3oTOiBblT
if I choose all stream sources (4), only two streams are visible on the main page.
TO BE
I should see all stream sources.
As a temporary solution, instead of all stream sources displayed in case of choosing 'my set' option, a simple 'my set' label is displayed.
> IOS-713: Adjustments for smaller screens

- Inbbbox/Source Files/Extensions/CollectionExtension.swift
- Inbbbox/Source Files/Extensions/GalleryViewProvider.swift
- Inbbbox/Source Files/Helpers/ManagedObjectsProvider.swift
- Inbbbox/Source Files/Managers/Animators/LoginViewAnimations.swift
- Inbbbox/Source Files/Model/Attachment.swift
- Inbbbox/Source Files/Model/ShotImage.swift
- Inbbbox/Source Files/Model/Team.swift
- Inbbbox/Source Files/Model/User.swift
- Inbbbox/Source Files/Networking/PageableComponent.swift
- Inbbbox/Source Files/Networking/Parameters.swift
- Inbbbox/Source Files/ViewControllers/SimpleShotsCollectionViewController.swift
- Podfile.lock
- README.md
Hello guys,
so I've been integrating another framework into separate build of Inbbbox today, but I experienced trouble building the project on my local machine running Xcode 8.3.3.
This pull request introduces Xcode 8.3.3 compliance thanks to:
- updating all dependencies to their latest versions in order to make the project build
- updating the codebase due to changes in the dependencies
- Swift 3.0 -> 3.1 conversion
- removing all deprecations and errors in the code
I have also introduced changes to README.md to point out at updated technical requirements for the project.
I hope you'll find this pull request useful. After merging that to development branch, a Bitrise build stack can be updated to Xcode 8.3.
> Make the project compliant with Xcode 8.3 and Swift 3.1
